### ISSUE TITLE
Issues creating new transformer

### ISSUE THREAD

**Issue by narkuss** [Alfresco/alfresco-helloworld-transformer#3] opened 2019-12-08 12:08 UTC
Hi all,
I've been trying to create a new transformer, based on alfresco-helloworld-transformer, as stated in documentation and projects README's and, by default, this project does not provide an ootb starting point for developing transformers, at least for me. I will post here all the problems I found.

- Parent dependency of alfresco-transform-core with version 2.1.0-EA4 causes a "Failure to find org.alfresco:alfresco-transform-model:jar:1.0.2.3" error when building. Changing to version 2.1.0 solved this error.
- Changing the java package naming caused a dependency failure for bean alfrescoSharedFileStoreClient, declared in abstractTransformerController. Related to this, it is not very clear in the docs, I think, the role of this docker image (I supposed it was only available for enterprise users)
- The fabric8 docker plugin gave me an error related to kubernetes, so I changed it for the com.spotify.dockerfile-maven-plugin.

Some of them are caused by my misunderstanding on how everything works for sure, but I think it could be useful for other people facing similar problems.

Thanks for your work!

**Comment by Epurashu** [comment] 2019-12-09 11:36
Hello :)
Thank you for raising this issue, I will start to investigate the problems mentioned above.

If you can please provide more info about the 3rd bullet point (fabric8 docker plugin), what error have you encountered and what version of Docker and OS are you using ?

**Comment by narkuss** [comment] 2019-12-09 20:39
Of course, here it goes:
OS: Ubuntu 18.04.3 LTS 4.15.0-72-generic
Docker:
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

The error I was getting was this. I have no kubernetes at all in my laptop:
`[INFO] --- fabric8-maven-plugin:4.3.1:build (build-image) @ alfresco-transformer ---
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc: El nom o servei no és conegut
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Building Container image with Docker in Kubernetes mode
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[INFO] Building tar: /home/marc/git/alfresco-ocr-transformer/target/docker/alfresco-transformer/1.0.0/tmp/docker-build.tar
[ERROR] F8: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.489 s
[INFO] Finished at: 2019-12-09T21:28:09+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.3.1:build (build-image) on project alfresco-transformer: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image -> [Help 1]`

I have to say that I decided to delete the parent declaration for alfresco-transform-core, the alfresco-core and dom4j dependencies, changed jdk from 11 to 8, and transformer is working fine. I like to clean up stuff I don't use or understand, if they're not necessary.

Hope it helps, good job everyone!

**Comment by Epurashu** [comment] 2019-12-10 14:52
Hello, here are some updates:

- _alfresco-transform-core_ version has been bumped to version 2.1.0 (released) in [PR#4](https://github.com/Alfresco/alfresco-helloworld-transformer/pull/4).

This fixes the `Failure to find org.alfresco:alfresco-transform-model:jar:1.0.2.3` problem. It slipped out because while creating this _hello-world_ example not all the code required by alfresco-transform-core was in the public maven repository, this should not be the case anymore.
<hr>

You are right about the `alfrescoSharedFileStoreClient`, it is used by the "enterprise part", but these T-engines can be used by 3 different Transform Services available in ACS 6.2:

- Legacy Transform Service - available in Community and Enterprise - sync transformation and sync renditions.
- Local Transform Service - available in Community and Enterprise - sync transformations and async renditions.
- Remote Transform Service - Enterprise only - async transformations and async renditions.

One of the advantages of adding _alfresco-transform-core_ dependency and have the custom T-engine Controller to extend _abstractTransformerController_ is that the code required to use each of the Transform Service mentioned above is already there.

The available documentation and this project (_alfresco-helloworld-transformer_) is designed for both community and enterprise developers.

I renamed locally _org.alfresco.transform_ package for the helloworld-transformer to something else and could reproduce the error:
`Field alfrescoSharedFileStoreClient in org.alfresco.transformer.AbstractTransformerController required a bean of type 'org.alfresco.transformer.clients.AlfrescoSharedFileStoreClient' that could not be found.
`
@CezarLeahu maybe this is something that we can further investigate ?
<hr>

By the Errors and Warning posted above I think you are referring to `fabric8-maven-plugin` and not `docker-maven-plugin`.

This kind of logs are normal when building docker images:
```
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host No such host is known (kubernetes.default.svc)
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Building Docker image in Kubernetes mode
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[INFO] Building tar: D:\work\alfresco-helloworld-transformer\alfresco-helloworld-transformer-engine\target\docker\alfresco\alfresco-helloworld-transformer\latest\tmp\docker-build.tar
[INFO] F8: [alfresco/alfresco-helloworld-transformer:latest]: Created docker-build.tar in 356 milliseconds
```
Unfortunately I saw different problems with this plugin depending on the version of Java, Docker, Maven and OS.
There are quite a few variables here and it is a little bit harder to investigate.
There are projects that will hang when building on a Windows 10 machine (I know the pain), I have no answer for this.
The reason we use this plugin is that it works perfectly on the build agents and we could not reproduce any of the problems that we had locally.

**Comment by narkuss** [comment] 2019-12-10 18:36
Hello,

Concerning fabric8 maven plugin, no problem, I'm using the other plugin, which I already used in other projects and, despite being discontinued, it does its job.

About pom dependencies, I find parent pom declaration (alfresco-transform-core) a bit strange, because alfresco-transformer-base already has this pom defined as parent in its pom. 
Adding only alfresco-transformer-base as a dependency in our transformer projects, gives us all this transitive dependencies declared in alfresco-transformer-base, and their versions are enforced by parent pom declaration of alfresco-transform-core in alfresco-transformer-base.

One last thing, in last comment I said I changed to jdk8. That's not true, I was using jdk11 all the time. In fact, using jdk8 gave a dependency error because of java versions at compilation time.

Thanks for your explanation about transformer's differences, it was great. I think it should be writen wherever it has more visibility.

**Comment by HansDeBal** [comment] 2020-05-14 06:37
I confirm the fabric8 plugin didn't work for me either! 
`INFO: I/O exception (java.io.IOException) caught when processing request to {}->unix://127.0.0.1:1: Broken pipe`
Replaced it with the spotify-plugin, worked like a charm.

**Comment by alandavis** [comment] 2020-06-06 06:21
To use the fabric8 plugin you may need to set the experimental feature to true in your locally installed docker.

{
  "experimental": true,
  "debug": true
}

**Comment by eknizat** [comment] 2020-08-10 14:53
I have updated the T-Engine README.md on how to address the above issues, in summary: 

Re fabric8: we will leave the fabric8 plugin for now as there are other options available if need be (the use of the fabric8 plugin is not mandatory) and other options might not work for everyone either.

Re the package renaming: Spring needs to know which packages to scan as we use dependency injections in some abstract classes which might be extended by classes in a non alfresco package. Spring offers several ways to do this, but a quick one would be to use @ComponentScan({"the.new.package", "org.alfresco.transformer"}) which would be added to your Application.java class. 

Can this issue be resolved now?

**Comment by HansDeBal** [comment] 2020-08-11 09:00
For me it can be resolved. We indeed  fixed it with the componentscan.

Thx for updating the instructions.

**Comment by montgolfiere** [comment] 2020-08-26 13:30
@alandavis @Epurashu I see you're both "assignees".

I don't have permission to resolve/close this issue. Can you do it please ? Thanks.

**Closed** 2020-08-26 13:38 UTC

**Comment by eknizat** [comment] 2020-08-26 13:39
Closing this issue as the highlighted problems have now been addressed.
